### HOSTNAME ###
hostname: "{{ inventory_hostname }}"

### VRFS ###
vrfs:
- name: default
  ip_routing: false
- name: ACME-DT
  ip_routing: true
- name: ACME-GENERAL
  ip_routing: true

### VLANS ###
vlans:
- id: 40
  name: ACME_GENERAL
- id: 50
  name: ACME_DT

### SVIS ###
vlan_interfaces:
- name: Vlan{{ hostvars[inventory_hostname].vars.srv_vlan }}
  description: "{{ hostvars[inventory_hostname].vars.srv_vrf }}"
  shutdown: false
  mtu: 1500
  vrf: "{{ hostvars[inventory_hostname].vars.srv_vrf }}"
  ip_address: "{{ hostvars[inventory_hostname].vars.srv_ip }}/24"

### MANAGEMENT INTERFACE ###
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: "{{ hostvars[inventory_hostname].vars.srv_mgmt_ip_addr }}/24"
  gateway: null
  type: oob

### ETHERNET INTERFACES ###
ethernet_interfaces:
  - name: Ethernet1
    vlans: "{{ hostvars[inventory_hostname].vars.srv_vlan }}"
    description: "{{ inventory_hostname }}_Ethernet"
    shutdown: false
    type: switched
    mode: access

### DEFAULT GATEWAY ###
static_routes:
- destination_address_prefix: 0.0.0.0/0
  vrf: "{{ hostvars[inventory_hostname].vars.srv_vrf }}"
  gateway: "{{ hostvars[inventory_hostname].vars.srv_gw }}"