all:
  children:
    cvp:
      hosts:
        cv_server:
          ansible_connection: httpapi
          ansible_host: 10.18.143.237
          ansible_httpapi_host: 10.18.143.237
          ansible_httpapi_port: 443
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_password: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjczNDY1MDc2Mjk1NjYzNjE3NTMsImRzbiI6ImN2cGFwaSIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3NDA4Mjg4NTgsImlhdCI6MTcxMDQ5ODg3Miwic2lkIjoiMTU2ZjVhOTQ3M2I0ZTUyYTdhZGE5ZGQ4NTE0MGRjYTM2YWMxMGZmOTYwYjlkOWVjNzRiMTAyMzRjMTYzYTgyNi1vSUJmRVROZVV5WnNEZ0c1WFdPTHc0MzJqOFlzWVJHZDBqQWVmUC1ZIn0.Rw6ZMcNqs9Ze1xnOvnMfhbPCSxlPx57iDQELew47f5R8MQXgs9Xz4vSIfLThZPh2No3NOVw3_bAbi1Rt6JRQIu7gbPG5AL_STUv-v8eTO5zWEUEI-jOv77S3voWwBO4drAJxsBqEnkNcmTSGQnmPT1vQZK-HGG7oUWe1e4w7GGVUgP-ovx3tpieK7Ln0mms9W8FEO1ZWEER-0XmxuJxZXHTNz4YcKymVJUUlicfXitLFrZMCbFDi6eFkG-WZJXo_mZb_7vBB6F5DWYjxgHZmdmqUTZ5oGeQuSF2cqeYd9462D9vQParZwx4_6ShRu3CKI0hIRjSgylMq9WIzqzVxZqWqihsfHtH6PE1w9egcSSbKVT25rhKg27c22zvClDrcQqvJXqG-rrQrthQ6yN9Vtw_sid-W3TofKsM_udoCQ8XKr9FMw3rAKKcvq5EnPRMOD0UBUUJ9_PVb0bCZxIpYHhW7loHCvbCP8AJUBm-9eSoF6iXwVnnaHB7ZRL7ph9GAJyL9fQDVHeVN6dxX38_DEcpIA2xpaAwk5sKgehrcqB5Do2HJC2POV-2iYtau-Xj1B2W4oIHqui4HzHkcU5gM1SEtlGUhMtdNXrN0TrkOb_HG6ZmoKGe6BtohNzAagVkXKFwLygysKmJ7w_8N8hidMZjuhyLUEppjJFgKgi5O2uY
          ansible_user: svc_account
        cv_ztp:
          ansible_host: 10.255.123.151
          ansible_password: cvproot
          ansible_user: root
    isis_fabric:
      children:
        dc01:
          children:
            core:
              hosts:
                core1:
                  vars:
                    svi_40: 10.4.1.1
                    svi_50: 10.5.1.1
                core2:
                  vars:
                    svi_40: 10.4.2.1
                    svi_50: 10.5.2.1
                core3:
                  vars:
                    svi_40: 10.4.3.1
                    svi_50: 10.5.3.1
                core4:
                  vars:
                    svi_40: 10.4.4.1
                    svi_50: 10.5.4.1
                core5:
                  vars:
                    svi_40: 10.4.5.1
                    svi_50: 10.5.5.1
                core6:
                  vars:
                    svi_40: 10.4.6.1
                    svi_50: 10.5.6.1
        servers:
          hosts:
            server01:
              vars:
                srv_gw: 10.4.1.1
                srv_ip: 10.4.1.101
                srv_mgmt_ip_addr: 192.168.0.135
                srv_vlan: 40
                srv_vrf: ACME-GENERAL
            server02:
              vars:
                srv_gw: 10.4.2.1
                srv_ip: 10.4.2.102
                srv_mgmt_ip_addr: 192.168.0.136
                srv_vlan: 40
                srv_vrf: ACME-GENERAL
            server03:
              vars:
                srv_gw: 10.4.3.1
                srv_ip: 10.4.3.103
                srv_mgmt_ip_addr: 192.168.0.137
                srv_vlan: 40
                srv_vrf: ACME-GENERAL
            server04:
              vars:
                srv_gw: 10.4.4.1
                srv_ip: 10.4.4.104
                srv_mgmt_ip_addr: 192.168.0.138
                srv_vlan: 40
                srv_vrf: ACME-GENERAL
            server05:
              vars:
                srv_gw: 10.4.5.1
                srv_ip: 10.4.5.105
                srv_mgmt_ip_addr: 192.168.0.139
                srv_vlan: 40
                srv_vrf: ACME-GENERAL
            server06:
              vars:
                srv_gw: 10.4.6.1
                srv_ip: 10.4.6.106
                srv_mgmt_ip_addr: 192.168.0.140
                srv_vlan: 40
                srv_vrf: ACME-GENERAL
            server07:
              vars:
                srv_gw: 10.5.1.1
                srv_ip: 10.5.1.107
                srv_mgmt_ip_addr: 192.168.0.141
                srv_vlan: 50
                srv_vrf: ACME-DT
            server08:
              vars:
                srv_gw: 10.5.2.1
                srv_ip: 10.5.2.108
                srv_mgmt_ip_addr: 192.168.0.142
                srv_vlan: 50
                srv_vrf: ACME-DT
            server09:
              vars:
                srv_gw: 10.5.3.1
                srv_ip: 10.5.3.109
                srv_mgmt_ip_addr: 192.168.0.143
                srv_vlan: 50
                srv_vrf: ACME-DT
            server10:
              vars:
                srv_gw: 10.5.4.1
                srv_ip: 10.5.4.110
                srv_mgmt_ip_addr: 192.168.0.144
                srv_vlan: 50
                srv_vrf: ACME-DT
            server11:
              vars:
                srv_gw: 10.5.5.1
                srv_ip: 10.5.5.111
                srv_mgmt_ip_addr: 192.168.0.145
                srv_vlan: 50
                srv_vrf: ACME-DT
            server12:
              vars:
                srv_gw: 10.5.6.1
                srv_ip: 10.5.6.112
                srv_mgmt_ip_addr: 192.168.0.146
                srv_vlan: 50
                srv_vrf: ACME-DT
          vars:
            type: server
      vars:
        ansible_become: true
        ansible_become_method: enable
        ansible_connection: httpapi
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_network_os: eos
        ansible_ssh_pass: arista1234
        ansible_user: cvpadmin
  vars:
    ansible_python_interpreter: python3
