---

  - hosts: dc01
    gather_facts: false
    tasks:
      - name: Generate Device Intended Config and Documention
        import_role:
          name: arista.avd.eos_cli_config_gen
      - name: Deploy Configurations to Device
        import_role: 
          name: arista.avd.eos_config_deploy_eapi